import convert from "https://cdn.jsdelivr.net/npm/convert@5";

const countryList = {
  AED: "AE",
  AFN: "AF",
  XCD: "AG",
  ALL: "AL",
  AMD: "AM",
  ANG: "AN",
  AOA: "AO",
  AQD: "AQ",
  ARS: "AR",
  AUD: "AU",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  XOF: "BE",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  NOK: "BV",
  BWP: "BW",
  BYR: "BY",
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  XAF: "CF",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUP: "CU",
  CVE: "CV",
  CYP: "CY",
  CZK: "CZ",
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DZD: "DZ",
  ECS: "EC",
  EEK: "EE",
  EGP: "EG",
  ETB: "ET",
  EUR: "FR",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GGP: "GG",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LTL: "LT",
  LVL: "LV",
  LYD: "LY",
  MAD: "MA",
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRO: "MR",
  MTL: "MT",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  XPF: "NC",
  NGN: "NG",
  NIO: "NI",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SKK: "SK",
  SLL: "SL",
  SOS: "SO",
  SRD: "SR",
  STD: "ST",
  SVC: "SV",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  UYU: "UY",
  UZS: "UZ",
  VEF: "VE",
  VND: "VN",
  VUV: "VU",
  YER: "YE",
  ZAR: "ZA",
  ZMK: "ZM",
  ZWD: "ZW",
};

const lengthList = {
  Kilometre: "km",
  Metre: "m",
  Decimetre: "dm",
  Centimetre: "cm",
  Millimetre: "mm",
  Micrometre: "μm",
  Nanometre: "nm",
  Picometre: "pm",
  Light_year: "ly",
  Parsec : "pc",
  Inch : "in",
  Mile : "mi",
  Foot : "ft",
  Yard : "yd",
  Nautical_mile : "nmi",
  Fathom : "fm"
}

const area = {
  Square_kilometre : "km²",
  Hectare : "ha",
  Are : "are",
  Square_metre : "m²",
  Square_decimetre: "dm²",
  Square_centimetre: "cm²",
  Square_millimetre: "mm²",
  Acre : "ac",
  Square_mile : "mi²",
  Square_yard : "yd²",
  Square_foot : "ft²",
  Square_inch : "in²"
}

const mass = {
  Kilogram : "kg",
  Gram : "g",
  Milligram : "mg",
  Microgram : "μg",
  Tonne : "t",
  Pound : "lb",
  Ounce : "oz",
  Grain : "gr",
  Long_ton : "long ton",
  Short_ton : "short ton",
  Stone : "st"
}

const tempreture = {
  Degree_Celsius : "C",
  Degree_Fahrenheit : "F",
  Degree_Rankine : "k",
  Kelvin : "K",
}

const pressure = {
  Standard_atmosphere : "atm",
  Hectopascal : "hPa",
  Kilopascal : "kPa",
  MegaPascal : "MPa",
  inch_of_mercury : "inHg",
  Bar : "bar",
  Millibar : "mbar",
  Pounds_per_square_inch : "psi"
}

const power = { 
  Watts : "W",
  Kilowatts : "kW",
  Megawatts : "MW",
  Gigawatts : "GW",
  Horsepower : "hp"
}

export {countryList,lengthList,area,mass,tempreture,pressure,power,convert};

